CREATE TABLE config (
	id INTEGER NOT NULL, 
	name VARCHAR, 
	"timeZone" VARCHAR, 
	path_api VARCHAR, 
	path_gui VARCHAR, 
	webapi_title VARCHAR, 
	webapi_description VARCHAR, 
	webapi_version VARCHAR, 
	webapi_openapi_url VARCHAR, 
	webapi_docs_url VARCHAR, 
	webapi_redoc_url VARCHAR, 
	webapi_key VARCHAR, 
	webapi_host VARCHAR, 
	webapi_port INTEGER, 
	webapi_workers INTEGER, 
	nginx_api_host VARCHAR, 
	nginx_api_port INTEGER, 
	nginx_api_key VARCHAR, 
	nginx_gui_host VARCHAR, 
	nginx_gui_port INTEGER, 
	nginx_gui_key VARCHAR, 
	git_email VARCHAR, 
	git_name VARCHAR, 
	git_key VARCHAR, 
	hotspod_ssid VARCHAR, 
	hotspod_ip VARCHAR, 
	hotspod_pass VARCHAR, 
	wifi_ssid VARCHAR, 
	wifi_ip VARCHAR, 
	wifi_pass VARCHAR, 
	debug BOOLEAN, 
	log BOOLEAN, 
	verbose BOOLEAN, 
	PRIMARY KEY (id)
);
